services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    networks:
      - shared-network

  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - uploads_data:/app/uploads
    networks:
      - shared-network

  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env
    container_name: luminest-db-1
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - shared-network

volumes:
  db_data:
  uploads_data:

networks:
  shared-network:
    external: true
    name: shared-apps